### PR TITLE
Feature cob perception msgs

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by fmessmer** [comment]
As this PR is not mergeable....but is only meant for backup purposes...I'd create a new branch on ipa320/people and merge it there - not indigo_dev

**Comment by fmessmer** [comment]
see #2 for a mergable PR
@ipa-fmw what are we going to do with it?

**Comment by floweisshardt** [comment]
@ipa-svn is separating the PR. so let's keep it open for a while for reference and then we can close it as soons as @ipa-svn finished

**Comment by fmessmer** [comment]
@ipa-frm-ag's work is backed-up on branch https://github.com/ipa320/people/tree/feature_cob_perception_msgs

@ipa-svn @ipa-fmw FYI
closing this one!

**Pull request closed without merging**
